dep_mode: depthcrafter
tap_mode: spatracker
flow_mode: raft
flow_ckpt: ./checkpoints/mosca/raft_models/raft-things.pth
tap_ckpt: ./checkpoints/mosca/spaT_final.pth

depthcrafter_unet_path: ./checkpoints/depthcrafter
depthcrafter_pretrain_path: ./checkpoints/stable-video-diffusion-img2vid-xt

metric3d_ckpt_path: ./checkpoints/metric3d/metric_depth_vit_giant2_800k.pth
metric3d_torch_hub_path: ./checkpoints/torch_hub_cache/Yvanyin_metric3d

# for dynamic denser TAP resample
epi_th: 0.0001
depth_boundary_th: 1.0

tap_chunk_size: 16384
n_track_uniform: 16384
n_track_dynamic: 16384

flow_steps: [1, 3]
epi_num_threads: 16 # Null

align_metric_flag: True
boundary_enhance_th: -1.0 # ! enhance boundary for spatracker
